[package]
name = "find-stale-translations"
version = "0.1.0"
authors = ["Tim Mulqueen <tim.mulqueen@messagebird.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
serde_json = "1.0.44"   